require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - 'app/helpers/**'
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'
Metrics/ClassLength:
  Max: 300
Metrics/MethodLength:
  Max: 20
Rails/EnumHash:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
RSpec/Rails/InferredSpecType:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 5
Style/BlockComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/QuotedSymbols:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false