inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - 'app/helpers/**'
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'
Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 20
Metrics/ClassLength:
  Max: 300
Metrics/MethodLength:
  Max: 20
Rails/EnumHash:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/PluckInWhere:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
RSpec/IndexedLet:
  Enabled: false
RSpec/Rails/InferredSpecType:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 5
RSpec/NestedGroups:
  Max: 4
Style/BlockComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never
RSpec/InstanceVariable:
  Enabled: false
Style/QuotedSymbols:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
