Metrics/AbcSize:
  Exclude:
    - 'app/services/filtro_por_ultima_donacion.rb'
    - 'app/services/informes.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/services/informes.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/services/filtro_por_atributo.rb'

Style/SafeNavigationChainLength:
  Exclude:
    - 'app/models/plantilla.rb'
