version: '3.3'
services:
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: wax-consilium
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    volumes:
      - .:/hemoclub
    ports:
      - "3000:3000"
    depends_on:
      - postgres
