FROM ruby:3.2.2
RUN apt update -qq
RUN curl -sLo https://deb.nodesource.com/setup_18.18.0 | bash
RUN apt install -y nodejs npm
RUN npm install -g yarn

ARG APP_VERSION
ENV RAILS_ENV development
ENV PROJECT_NAME hemoclub
WORKDIR /$PROJECT_NAME

RUN gem install bundler --no-document -v '2.4.10'
COPY Gemfile /$PROJECT_NAME/Gemfile
COPY Gemfile.lock /$PROJECT_NAME/Gemfile.lock
RUN bundle install

COPY package.json /$PROJECT_NAME/package.json
COPY yarn.lock /$PROJECT_NAME/yarn.lock
RUN yarn install
