require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/automatizaciones", type: :request do
  include Devise::Test::IntegrationHelpers

  # This should return the minimal set of attributes required to create a valid
  # Automatizacion. As you add validations to Automatizacion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { nombre: "una automatizacion", remitente: "mail@mail.com",
      lista_id: create(:lista).id, plantilla_id: create(:plantilla).id }
  end

  let(:invalid_attributes) do
    { nombre: "" }
  end

  before { sign_in Usuario.new }

  describe "GET /index" do
    it "renders a successful response" do
      Automatizacion.create! valid_attributes
      get automatizaciones_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      automatizacion = Automatizacion.create! valid_attributes
      get automatizacion_url(automatizacion)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_automatizacion_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      automatizacion = Automatizacion.create! valid_attributes
      get edit_automatizacion_url(automatizacion)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Automatizacion" do
        expect do
          post automatizaciones_url, params: { automatizacion: valid_attributes }
        end.to change(Automatizacion, :count).by(1)
      end

      it "redirects to the created automatizacion" do
        post automatizaciones_url, params: { automatizacion: valid_attributes }
        expect(response).to redirect_to(automatizacion_url(Automatizacion.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Automatizacion" do
        expect do
          post automatizaciones_url, params: { automatizacion: invalid_attributes }
        end.not_to change(Automatizacion, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post automatizaciones_url, params: { automatizacion: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        { nombre: "otra automatizacion" }
      end

      it "updates the requested automatizacion" do
        automatizacion = Automatizacion.create! valid_attributes
        patch automatizacion_url(automatizacion), params: { automatizacion: new_attributes }
        automatizacion.reload
        expect(automatizacion.nombre).to eq new_attributes[:nombre]
      end

      it "redirects to the automatizacion" do
        automatizacion = Automatizacion.create! valid_attributes
        patch automatizacion_url(automatizacion), params: { automatizacion: new_attributes }
        automatizacion.reload
        expect(response).to redirect_to(automatizacion_url(automatizacion))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        automatizacion = Automatizacion.create! valid_attributes
        patch automatizacion_url(automatizacion), params: { automatizacion: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested automatizacion" do
      automatizacion = Automatizacion.create! valid_attributes
      expect do
        delete automatizacion_url(automatizacion)
      end.to change(Automatizacion, :count).by(-1)
    end

    it "redirects to the automatizaciones list" do
      automatizacion = Automatizacion.create! valid_attributes
      delete automatizacion_url(automatizacion)
      expect(response).to redirect_to(automatizaciones_url)
    end
  end
end
