require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/difusiones", type: :request do
  include Devise::Test::IntegrationHelpers

  # This should return the minimal set of attributes required to create a valid
  # Difusion. As you add validations to Difusion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { nombre: "una difusion", lista_dinamica_id: create(:lista_dinamica).id, plantilla_id: create(:plantilla).id }
  end

  let(:invalid_attributes) do
    { nombre: "" }
  end

  before { sign_in Usuario.new }

  describe "GET /index" do
    it "renders a successful response" do
      Difusion.create! valid_attributes
      get difusiones_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      difusion = Difusion.create! valid_attributes
      get difusion_url(difusion)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_difusion_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      difusion = Difusion.create! valid_attributes
      get edit_difusion_url(difusion)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Difusion" do
        expect do
          post difusiones_url, params: { difusion: valid_attributes }
        end.to change(Difusion, :count).by(1)
      end

      it "redirects to the created difusion" do
        post difusiones_url, params: { difusion: valid_attributes }
        expect(response).to redirect_to(difusion_url(Difusion.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Difusion" do
        expect do
          post difusiones_url, params: { difusion: invalid_attributes }
        end.not_to change(Difusion, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post difusiones_url, params: { difusion: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        { nombre: "otra difusion" }
      end

      it "updates the requested difusion" do
        difusion = Difusion.create! valid_attributes
        patch difusion_url(difusion), params: { difusion: new_attributes }
        difusion.reload
        expect(difusion.nombre).to eq new_attributes[:nombre]
      end

      it "redirects to the difusion" do
        difusion = Difusion.create! valid_attributes
        patch difusion_url(difusion), params: { difusion: new_attributes }
        difusion.reload
        expect(response).to redirect_to(difusion_url(difusion))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        difusion = Difusion.create! valid_attributes
        patch difusion_url(difusion), params: { difusion: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested difusion" do
      difusion = Difusion.create! valid_attributes
      expect do
        delete difusion_url(difusion)
      end.to change(Difusion, :count).by(-1)
    end

    it "redirects to the difusiones list" do
      difusion = Difusion.create! valid_attributes
      delete difusion_url(difusion)
      expect(response).to redirect_to(difusiones_url)
    end
  end
end
