require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/exclusiones_tipicas", type: :request do
  include Devise::Test::IntegrationHelpers
  # This should return the minimal set of attributes required to create a valid
  # ExclusionTipica. As you add validations to ExclusionTipica, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { motivo: "Tatuaje", duracion: 6 }
  end

  let(:invalid_attributes) do
    { duracion: "uno" }
  end

  before { sign_in Usuario.new }

  describe "GET /index" do
    it "renders a successful response" do
      ExclusionTipica.create! valid_attributes
      get exclusiones_tipicas_url
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_exclusion_tipica_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      exclusion_tipica = ExclusionTipica.create! valid_attributes
      get edit_exclusion_tipica_url(exclusion_tipica)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExclusionTipica" do
        expect do
          post exclusiones_tipicas_url, params: { exclusion_tipica: valid_attributes }
        end.to change(ExclusionTipica, :count).by(1)
      end

      it "redirects to the index" do
        post exclusiones_tipicas_url, params: { exclusion_tipica: valid_attributes }
        expect(response).to redirect_to(exclusiones_tipicas_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExclusionTipica" do
        expect do
          post exclusiones_tipicas_url, params: { exclusion_tipica: invalid_attributes }
        end.not_to change(ExclusionTipica, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post exclusiones_tipicas_url, params: { exclusion_tipica: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        { duracion: 12 }
      end

      it "updates the requested exclusion_tipica" do
        exclusion_tipica = ExclusionTipica.create! valid_attributes
        patch exclusion_tipica_url(exclusion_tipica), params: { exclusion_tipica: new_attributes }
        exclusion_tipica.reload
        expect(exclusion_tipica.duracion).to eq 12
      end

      it "redirects to the exclusion_tipica" do
        exclusion_tipica = ExclusionTipica.create! valid_attributes
        patch exclusion_tipica_url(exclusion_tipica), params: { exclusion_tipica: new_attributes }
        exclusion_tipica.reload
        expect(response).to redirect_to(exclusiones_tipicas_url)
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        exclusion_tipica = ExclusionTipica.create! valid_attributes
        patch exclusion_tipica_url(exclusion_tipica), params: { exclusion_tipica: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested exclusion_tipica" do
      exclusion_tipica = ExclusionTipica.create! valid_attributes
      expect do
        delete exclusion_tipica_url(exclusion_tipica)
      end.to change(ExclusionTipica, :count).by(-1)
    end

    it "redirects to the exclusiones_tipicas list" do
      exclusion_tipica = ExclusionTipica.create! valid_attributes
      delete exclusion_tipica_url(exclusion_tipica)
      expect(response).to redirect_to(exclusiones_tipicas_url)
    end
  end
end
