require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/listas_dinamicas", type: :request do
  include Devise::Test::IntegrationHelpers

  # This should return the minimal set of attributes required to create a valid
  # ListaDinamica. As you add validations to ListaDinamica, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      nombre: "un nombre",
      filtro_attributes: {
        condiciones: { "s" => "tipo_donante asc" },
        nombre: "un filtro"
      }
    }
  end

  let(:invalid_attributes) do
    { nombre: "" }
  end

  before { sign_in Usuario.new }

  describe "GET /index" do
    it "renders a successful response" do
      ListaDinamica.create! valid_attributes
      get listas_dinamicas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lista_dinamica = ListaDinamica.create! valid_attributes
      get lista_dinamica_url(lista_dinamica)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lista_dinamica_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      lista_dinamica = ListaDinamica.create! valid_attributes
      get edit_lista_dinamica_url(lista_dinamica)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ListaDinamica" do
        expect do
          post listas_dinamicas_url, params: { lista_dinamica: valid_attributes }
        end.to change(ListaDinamica, :count).by(1)
                                            .and change(Filtro, :count).by(1)
      end

      it "redirects to the created lista dinamica" do
        post listas_dinamicas_url, params: { lista_dinamica: valid_attributes }
        expect(response).to redirect_to(lista_dinamica_url(ListaDinamica.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ListaDinamica" do
        expect do
          post listas_dinamicas_url, params: { lista_dinamica: invalid_attributes }
        end.not_to change(ListaDinamica, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post listas_dinamicas_url, params: { lista_dinamica: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        { nombre: "otro nombre" }
      end

      it "updates the requested lista dinamica" do
        lista_dinamica = ListaDinamica.create! valid_attributes
        patch lista_dinamica_url(lista_dinamica), params: { lista_dinamica: new_attributes }
        lista_dinamica.reload
        expect(lista_dinamica.nombre).to eq new_attributes[:nombre]
      end

      it "redirects to the lista dinamica" do
        lista_dinamica = ListaDinamica.create! valid_attributes
        patch lista_dinamica_url(lista_dinamica), params: { lista_dinamica: new_attributes }
        lista_dinamica.reload
        expect(response).to redirect_to(lista_dinamica_url(lista_dinamica))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        lista_dinamica = ListaDinamica.create! valid_attributes
        patch lista_dinamica_url(lista_dinamica), params: { lista_dinamica: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lista dinamica" do
      lista_dinamica = ListaDinamica.create! valid_attributes
      expect do
        delete lista_dinamica_url(lista_dinamica)
      end.to change(ListaDinamica, :count).by(-1)
    end

    it "redirects to the listas dinamicas list" do
      lista_dinamica = ListaDinamica.create! valid_attributes
      delete lista_dinamica_url(lista_dinamica)
      expect(response).to redirect_to(listas_dinamicas_url)
    end
  end
end
