require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/plantillas", type: :request do
  include Devise::Test::IntegrationHelpers

  # This should return the minimal set of attributes required to create a valid
  # Plantilla. As you add validations to Plantilla, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { nombre: "Una plantilla", contenido: "<p>MyString<p/>" } }

  let(:invalid_attributes) { { contenido: "" } }

  before { sign_in Usuario.new }

  describe "GET /index" do
    it "renders a successful response" do
      Plantilla.create! valid_attributes
      get plantillas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      plantilla = Plantilla.create! valid_attributes
      get plantilla_url(plantilla)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_plantilla_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      plantilla = Plantilla.create! valid_attributes
      get edit_plantilla_url(plantilla)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Plantilla" do
        expect do
          post plantillas_url, params: { plantilla: valid_attributes }
        end.to change(Plantilla, :count).by(1)
      end

      it "redirects to the created plantilla" do
        post plantillas_url, params: { plantilla: valid_attributes }
        expect(response).to redirect_to(plantilla_url(Plantilla.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Plantilla" do
        expect do
          post plantillas_url, params: { plantilla: invalid_attributes }
        end.not_to change(Plantilla, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post plantillas_url, params: { plantilla: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) { { contenido: "<p>Other string<p/>" } }

      it "updates the requested plantilla" do
        plantilla = Plantilla.create! valid_attributes
        patch plantilla_url(plantilla), params: { plantilla: new_attributes }
        plantilla.reload
        expect(plantilla.contenido).to eq new_attributes[:contenido]
      end

      it "redirects to the plantilla" do
        plantilla = Plantilla.create! valid_attributes
        patch plantilla_url(plantilla), params: { plantilla: new_attributes }
        plantilla.reload
        expect(response).to redirect_to(plantilla_url(plantilla))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        plantilla = Plantilla.create! valid_attributes
        patch plantilla_url(plantilla), params: { plantilla: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested plantilla" do
      plantilla = Plantilla.create! valid_attributes
      expect do
        delete plantilla_url(plantilla)
      end.to change(Plantilla, :count).by(-1)
    end

    it "redirects to the plantillas list" do
      plantilla = Plantilla.create! valid_attributes
      delete plantilla_url(plantilla)
      expect(response).to redirect_to(plantillas_url)
    end
  end
end
