toolbar:
  - undo redo | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor | emoticons | image link
  - h1 | h2 | h3 | h4 | h5 | h6
plugins:
  - preview autolink image link nonbreaking advlist lists emoticons
promotion: false
language: es_MX
relative_urls: false
remove_script_host: false
convert_urls: true