# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Clinica.create(nombre: "ASOC ESPAÑOLA DE SOCORROS MUTU", codigo: 132)
Clinica.create(nombre: "BAZTERRICA", codigo: 2)
Clinica.create(nombre: "C. MEDICO INTEGRAL FITZ ROY", codigo: 30)
Clinica.create(nombre: "C.DIALISIS- DR.PEDRO DI SPAGNA", codigo: 107)
Clinica.create(nombre: "CARDIOVASCULAR INFANTIL", codigo: 152)
Clinica.create(nombre: "CCP BAIRES", codigo: 535)
Clinica.create(nombre: "CEMIC", codigo: 13)
Clinica.create(nombre: "CENTENARIO S.A.", codigo: 108)
Clinica.create(nombre: "CENTRO DE GALICIA SALUD", codigo: 130)
Clinica.create(nombre: "CENTRO DEL PARQUE", codigo: 536)
Clinica.create(nombre: "CENTRO MEDICO SAENZ PEÑA", codigo: 106)
Clinica.create(nombre: "CENTRO MEDICUS", codigo: 110)
Clinica.create(nombre: "CLINICA AMEBPBA-BCO PROVINCIA", codigo: 192)
Clinica.create(nombre: "CLINICA 1° DE MAYO OSEIV", codigo: 9)
Clinica.create(nombre: "CLINICA ADVENTISTA BELGRANO", codigo: 50)
Clinica.create(nombre: "CLINICA CIAREC", codigo: 137)
Clinica.create(nombre: "CLINICA DE LA MICROCIRUGIA", codigo: 104)
Clinica.create(nombre: "CLINICA DE LA PROVIDENCIA", codigo: 103)
Clinica.create(nombre: "CLINICA DEL GOLF", codigo: 153)
Clinica.create(nombre: "CLINICA DEL ROSARIO", codigo: 22)
Clinica.create(nombre: "CLINICA DEL SOL", codigo: 6)
Clinica.create(nombre: "CLINICA ITEBA", codigo: 134)
Clinica.create(nombre: "CLINICA LA ESPERANZA", codigo: 12)
Clinica.create(nombre: "CLINICA LOPEZ-CTRO.DE MED. INT", codigo: 38)
Clinica.create(nombre: "CLINICA MAYO", codigo: 19)
Clinica.create(nombre: "CLINICA PASTELEROS", codigo: 200)
Clinica.create(nombre: "CLINICA PRIVADA DEL PILAR", codigo: 40)
Clinica.create(nombre: "CLINICA SANTA CATALINA", codigo: 100)
Clinica.create(nombre: "CLINICA UNO ANEXO HTAL FRANCES", codigo: 131)
Clinica.create(nombre: "CLUB DE DONANTES", codigo: 28)
Clinica.create(nombre: "COLECTA EXTERNA", codigo: 99)
Clinica.create(nombre: "CONICET", codigo: 527)
Clinica.create(nombre: "CTRO.MED. DE CIR.PLAST.DR. CAR", codigo: 26)
Clinica.create(nombre: "CTRO.MED. SAN JERONIMO", codigo: 20)
Clinica.create(nombre: "DENTON COOLEY", codigo: 143)
Clinica.create(nombre: "DOMICILIO", codigo: 18)
Clinica.create(nombre: "DONANTE VOLUNTARIO", codigo: 29)
Clinica.create(nombre: "DONANTE VOLUNTARIO CIMER", codigo: 23)
Clinica.create(nombre: "DONANTE VOLUNTARIO FAVALORO", codigo: 528)
Clinica.create(nombre: "DR. ROBERTO VEITZ", codigo: 109)
Clinica.create(nombre: "DRA. VOTO", codigo: 11)
Clinica.create(nombre: "FU.HE.SA.", codigo: 4)
Clinica.create(nombre: "FUNDACION FAVALORO", codigo: 160)
Clinica.create(nombre: "FUNDACION HEMOCENTRO OESTE", codigo: 156)
Clinica.create(nombre: "FUNDACION INFANT", codigo: 533)
Clinica.create(nombre: "FUNDALEU", codigo: 534)
Clinica.create(nombre: "HEMOCENTRO", codigo: 1)
Clinica.create(nombre: "HOSP DE BOLIVAR DR CAPREDONI", codigo: 193)
Clinica.create(nombre: "HOSPITAL ALEMAN", codigo: 163)
Clinica.create(nombre: "HOSPITAL AUSTRAL", codigo: 154)
Clinica.create(nombre: "HOSPITAL BRITANICO", codigo: 524)
Clinica.create(nombre: "HOSPITAL CHURRUCA", codigo: 529)
Clinica.create(nombre: "HOSPITAL DE CLINICAS", codigo: 102)
Clinica.create(nombre: "HOSPITAL DR.L. PIÑERO", codigo: 522)
Clinica.create(nombre: "HOSPITAL FERNANDEZ", codigo: 10)
Clinica.create(nombre: "HOSPITAL MILITAR", codigo: 538)
Clinica.create(nombre: "HOSPITAL NAVAL", codigo: 525)
Clinica.create(nombre: "HOSPITAL PENNA", codigo: 532)
Clinica.create(nombre: "HOSPITAL PRIVADO MODELO", codigo: 17)
Clinica.create(nombre: "HOSPITAL SIRIO LIBANES", codigo: 136)
Clinica.create(nombre: "HOSPITAL VELEZ SARFIELD", codigo: 531)
Clinica.create(nombre: "HTAL A GRAL M BELGRANO", codigo: 113)
Clinica.create(nombre: "I.C.A. DE JUNIN", codigo: 523)
Clinica.create(nombre: "I.M.E.C.C.", codigo: 139)
Clinica.create(nombre: "I.M.O.S.", codigo: 36)
Clinica.create(nombre: "IADT-INST. DE DIAGNOSTICO Y TR", codigo: 14)
Clinica.create(nombre: "IMAC", codigo: 111)
Clinica.create(nombre: "INST.MED. RODRIGUEZ PEÑA", codigo: 39)
Clinica.create(nombre: "INST.MEDICO DE OBSTETRICIA SA", codigo: 37)
Clinica.create(nombre: "INSTITUTO ASSAL", codigo: 135)
Clinica.create(nombre: "INSTITUTO CARDIOVASCULAR BS AS", codigo: 520)
Clinica.create(nombre: "INSTITUTO FLENI", codigo: 155)
Clinica.create(nombre: "INTITUTO DEL CORAZON A. COOLEZ", codigo: 21)
Clinica.create(nombre: "NEFROLOGY", codigo: 138)
Clinica.create(nombre: "OSPLAD", codigo: 521)
Clinica.create(nombre: "PLASMIUM", codigo: 162)
Clinica.create(nombre: "POLICLINICO BANCARIO", codigo: 142)
Clinica.create(nombre: "PURISSIMUS S.A.", codigo: 25)
Clinica.create(nombre: "ROSSAROLI SERGIO", codigo: 112)
Clinica.create(nombre: "SAGRADA FAMILIA", codigo: 514)
Clinica.create(nombre: "SANATORIO A. FLEMING", codigo: 15)
Clinica.create(nombre: "SANATORIO ARGENTINO", codigo: 105)
Clinica.create(nombre: "SANATORIO ASIMRA", codigo: 7)
Clinica.create(nombre: "SANATORIO DE LA PIEDAD", codigo: 133)
Clinica.create(nombre: "SANATORIO FINOCHIETTO", codigo: 161)
Clinica.create(nombre: "SANATORIO FRANCHIN", codigo: 194)
Clinica.create(nombre: "SANATORIO GUEMES", codigo: 196)
Clinica.create(nombre: "SANATORIO MITRE", codigo: 24)
Clinica.create(nombre: "SANATORIO MORANO", codigo: 8)
Clinica.create(nombre: "SANATORIO OTAMENDI", codigo: 141)
Clinica.create(nombre: "SANATORIO PRIVADO DEL CENTRO", codigo: 140)
Clinica.create(nombre: "SANATORIO SAN CAYETANO", codigo: 157)
Clinica.create(nombre: "SANATORIO SAN JOSE", codigo: 518)
Clinica.create(nombre: "SANATORIO SANTA ISABEL", codigo: 35)
Clinica.create(nombre: "SANTA ANA", codigo: 3)
Clinica.create(nombre: "TRINIDAD PALERMO", codigo: 27)
Clinica.create(nombre: "TRINIDAD SAN ISIDRO FLEMING", codigo: 195)
Clinica.create(nombre: "TRINIDAD SAN ISIDRO THAMES", codigo: 5)
Clinica.create(nombre: "UNID ASIST MILSTEIN", codigo: 537)