name: Deploy production

on:
  release:
    types: [published]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: cschleiden/replace-tokens@v1
        with:
          files: 'azure.yaml'
        env:
          IMAGE_VERSION: ${{ github.ref_name }}

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          yamlConfigPath: azure.yaml
          containerAppName: hemoclub-containerapp
          resourceGroup: SOFTFHBA
          imageToDeploy: docker.io/joaquincasal/fhba-mkt:${{ github.ref_name }}