name: Deploy production

on:
  release:
    types: [published]

jobs:
  deploy-production:
    runs-on: ubuntu-22.04
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: cschleiden/replace-tokens@v1
        with:
          files: 'azure.yaml'
        env:
          IMAGE_VERSION: ${{ github.ref_name }}

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          yamlConfigPath: azure.yaml
          containerAppName: hemoclub-containerapp
          resourceGroup: SOFTFHBA
          imageToDeploy: docker.io/joaquincasal/hemoclub:${{ github.ref_name }}
          registryUrl: docker.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.DOCKERHUB_TOKEN }}
